trigger:
  branches:
    include:
      - master
      - dev/*
  paths:
    exclude:
      - README.md
      - images-doc/*

variables:
  poolDeployName: HomeServers
  imageName: "registry.gitlab.com/ricardosantos9521/chat/frontend"
  buildId: $(Build.BuildNumber)
  dockerRegistryEndpoint: "GitLab Registry"

stages:
- stage: Build
  jobs:
  - job: BuildJob
    pool: $(poolDeployName)
    steps:
    - task: Docker@1
      displayName: "Build an image"
      inputs:
        command: "Build an image"
        imageName: $(imageName):$(buildId)
        dockerFile: Dockerfile
        includeLatestTag: true
    - task: Docker@1
      inputs:
        command: "Push an image"
        imageName: $(imageName):$(buildId)
        containerregistrytype: "Container Registry"
        dockerRegistryEndpoint: $(dockerRegistryEndpoint)
    - task: Docker@1
      inputs:
        command: "Push an image"
        imageName: $(imageName):latest
        containerregistrytype: "Container Registry"
        dockerRegistryEndpoint: $(dockerRegistryEndpoint)
    - task: kasunkodagoda.regex-match-replace.regex-match-replace.RegExMatchReplace@2
      displayName: "RegEx Match & Replace"
      inputs:
        PathToFile: "deployment.yaml"
        RegEx: BUILDNUMBER
        ValueToReplace: "$(Build.BuildNumber)"
    - task: CopyFiles@2
      displayName: "Copy Kubernetes (yaml) to artifacts"
      inputs:
        contents: "*.yaml"
        overWrite: true
        targetFolder: $(Pipeline.Workspace)/artifacts
    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: '$(Pipeline.Workspace)/artifacts'
        artifact: pipeline

- stage: Deploy
  dependsOn: Build
  condition: succeeded('Build')
  jobs:
  - deployment: DeployJob
    environment: "chat-frontend deploy"
    pool: $(poolDeployName)
    strategy:
      runOnce:
        deploy:
          steps:
          - task: Kubernetes@1
            displayName: "Create namespace if don't exist"
            inputs:
              connectionType: "None"
              command: "apply"
              useConfigurationFile: true
              configuration: "$(Pipeline.Workspace)/pipeline/namespace.yaml"
          - task: Kubernetes@1
            displayName: "Apply changes"
            inputs:
              connectionType: "None"
              namespace: chat
              command: "apply"
              useConfigurationFile: true
              configuration: "$(Pipeline.Workspace)/pipeline/deployment.yaml"
              secretType: "dockerRegistry"
              containerRegistryType: "Container Registry"
              dockerRegistryEndpoint: $(dockerRegistryEndpoint)
              secretName: "gitlabdockersecret"
