trigger:
  branches:
    include:
      - master
      - dev/*
  paths:
    exclude:
      - README.md
      - images-doc/*

variables:
  poolDeployName: HomeServers
  imageName: "registry.gitlab.com/ricardosantos9521/chat/frontend:$(Build.BuildNumber)"
  dockerRegistryEndpoint: "GitLab Registry"

stages:
- stage: Build
  jobs:
  - job: BuildJob
    pool:
      vmImage: "ubuntu-latest"
    steps:
      - task: Docker@1
        displayName: "Build an image"
        inputs:
          command: "Build an image"
          imageName: $(imageName)
          dockerFile: Dockerfile
      - task: Docker@1
        displayName: "Push an image"
        inputs:
          containerregistrytype: "Container Registry"
          command: "Push an image"
          imageName: $(imageName)
          dockerFile: Dockerfile
          dockerRegistryEndpoint: $(dockerRegistryEndpoint)
      - task: kasunkodagoda.regex-match-replace.regex-match-replace.RegExMatchReplace@2
        displayName: "RegEx Match & Replace"
        inputs:
          PathToFile: "deployment.yaml"
          RegEx: BUILDNUMBER
          ValueToReplace: "$(Build.BuildNumber)"
      - task: CopyFiles@1
        displayName: copy kubernetes yaml
        inputs:
          contents: "*.yaml"
          targetFolder: $(Pipeline.Workspace)
      - task: PublishPipelineArtifact@1
        inputs:
          targetPath: '$(Pipeline.Workspace)'
          artifact: pipeline

- stage: Deploy
  dependsOn: Build
  jobs:
  - deployment: DeployJob
    environment: "chat-frontend deploy"
    pool: $(poolDeployName)
    strategy:
      runOnce:
        deploy:
          steps:
          - task: Kubernetes@1
            displayName: "Create namespace if don't exist"
            inputs:
              connectionType: "None"
              command: "apply"
              useConfigurationFile: true
              configuration: "$(Pipeline.Workspace)/pipeline/namespace.yaml"
          - task: Kubernetes@1
            displayName: "Apply changes"
            inputs:
              connectionType: "None"
              namespace: chat
              command: "apply"
              useConfigurationFile: true
              configuration: "$(Pipeline.Workspace)/pipeline/deployment.yaml"
              secretType: "dockerRegistry"
              containerRegistryType: "Container Registry"
              dockerRegistryEndpoint: $(dockerRegistryEndpoint)
              secretName: "gitlabdockersecret"
