pool: HomeServers

trigger:
- master

steps:
- task: Docker@1
  displayName: 'Build an image'
  inputs:
    containerregistrytype: 'Container Registry'
    command: 'Build an image'
    imageName: 'registry.gitlab.com/ricardosantos9521/github/signalrclient:$(Build.BuildNumber)'
    dockerFile: Dockerfile
    dockerRegistryEndpoint: teamrics

- task: Docker@1
  displayName: 'Push an image'
  inputs:
    containerregistrytype: 'Container Registry'
    command: 'Push an image'
    imageName: 'registry.gitlab.com/ricardosantos9521/github/signalrclient:$(Build.BuildNumber)'
    dockerFile: Dockerfile
    dockerRegistryEndpoint: teamrics

- task: CopyFiles@1
  displayName: copy kubernetes yaml
  inputs: 
    contents: "deployment.yaml"
    targetFolder: $(Build.ArtifactStagingDirectory)

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: drop

      