apiVersion: apps/v1
kind: Deployment
metadata:
  name: chattestclient-dpl
spec:
  replicas: 1
  revisionHistoryLimit: 1
  strategy:
    rollingUpdate:
      maxUnavailable: 50%
      maxSurge: 2
  selector:
    matchLabels:
      app: chattestclient
  template:
    metadata:
       labels:
         app: chattestclient
    spec:
      containers:
      - name: chattestclient
        image: "registry.gitlab.com/ricardosantos9521/github/chattest.client:BUILDNUMBER"
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: "100Mi"
            cpu: "60m"
        readinessProbe:
          httpGet:
             path: /
             port: 80
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
      imagePullSecrets:
        - name: secretteamrics
---
apiVersion: v1
kind: Service
metadata:
  name: chattestclient-svc
spec:
  selector:
    app: chattestclient
  ports:
  - port: 80
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: chattestclient-ing
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    # nginx.ingress.kubernetes.io/add-base-url: "true"
    # nginx.ingress.kubernetes.io/ingress.allow-http: "true"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  tls:
  - hosts:
    - rics.synology.me
    secretName: tlscert
  rules:
  - host: rics.synology.me
    http:
      paths:
      - path: /chat/client/(.*)
        backend:
          serviceName: chattestclient-svc
          servicePort: 80