apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-frontend-dpl
  namespace: chat
spec:
  replicas: 1
  revisionHistoryLimit: 1
  strategy:
    rollingUpdate:
      maxUnavailable: 50%
      maxSurge: 2
  selector:
    matchLabels:
      app: chat-frontend-app
  template:
    metadata:
      labels:
        app: chat-frontend-app
    spec:
      containers:
        - name: chat-frontend-container
          image: "registry.gitlab.com/ricardosantos9521/chat/frontend:BUILDNUMBER"
          ports:
            - containerPort: 80
          resources:
            limits:
              memory: "100Mi"
              cpu: "60m"
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
      imagePullSecrets:
        - name: gitlabdockersecret
---
apiVersion: v1
kind: Service
metadata:
  name: chat-frontend-svc
  namespace: chat
spec:
  selector:
    app: chat-frontend-app
  ports:
    - port: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: chat-frontend-ing
  namespace: chat
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  rules:
    - host: ricspt.ddns.net
      http:
        paths:
          - path: /chat/frontend(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: chat-frontend-svc
                port:
                  number: 80
