apiVersion: apps/v1
kind: Deployment
metadata:
  name: signalrclient-dpl
spec:
  replicas: 1
  revisionHistoryLimit: 1
  strategy:
    rollingUpdate:
      maxUnavailable: 50%
      maxSurge: 2
  selector:
    matchLabels:
      app: signalrclient
  template:
    metadata:
       labels:
         app: signalrclient
    spec:
      containers:
      - name: signalrclient
        image: "registry.gitlab.com/ricardosantos9521/github/signalrclient:BUILDNUMBER"
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: "100Mi"
            cpu: "100m"
        readinessProbe:
          httpGet:
             path: /
             port: 80
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
      imagePullSecrets:
        - name: secretteamrics
---
apiVersion: v1
kind: Service
metadata:
  name: signalrclient-svc
spec:
  selector:
    app: signalrclient
  ports:
  - port: 80
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: signalrclient-ing
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    # nginx.ingress.kubernetes.io/add-base-url: "true"
    # nginx.ingress.kubernetes.io/ingress.allow-http: "true"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  rules:
  - http:
      paths:
      - path: /signalr/client/
        backend:
          serviceName: signalrclient-svc
          servicePort: 80